version: '3.8'
services:
  prod:
    container_name: intellisense
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start
    ports:
      - 8080:8080
    volumes:
      - .:/user/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
